### ISSUE TITLE
[Request] Allow limiting cache size

### ISSUE THREAD

**Issue by hackel** [cachapa/AerialDream#1]
I'm running Aerial Dream on my Nexus Player that only has 8G of internal storage.  Currently, the Aerial Dream cache takes up 1.8G of that.  It would be great if there was a setting or some other way to limit the space used by the cache or disable it entirely so that I don't have to continually empty it manually.

PS--love the app.  It really makes my screen beautiful, especially while listening to music!

**Comment by cachapa** [comment]
(Sorry for taking so long to respond. Turns out GitHub doesn't subscribe you automatically to your own repos, so I didn't get a notification from your message)

Yeah, I've also run into this in my Nexus Player.

I'm still undecided on how to best solve this. I believe that AppleTV simply streams the content the entire time without caching, so that'd be the easy option.

That's wasteful though, so I'd like to keep some form of caching option available, ideally presenting the user with a list of available videos where he would be able to choose which to keep locally.

**Comment by hackel** [comment]
I agree, it is horribly wasteful, especially for anyone with a metered internet connection.  Being able to select specific videos would be great, though quite a bit more work I would imagine.  If there was a simple cache size setting, then it could just cycle through only the videos have already been downloaded,  in whatever random order it usually uses.

Another option would be the possibility to set a proxy server, so that I could store the videos elsewhere on my LAN and stream them to the device when needed.

**Comment by cachapa** [comment]
There's an option to limit the cache size. Honestly it's not terribly well tested but I'll close this for now.
