### ISSUE TITLE
2017 source option is applied to 2018 and 2019 videos

### ISSUE THREAD

**Issue by Dreamescaper** [cachapa/AerialDream#23]
In `VideoController.loadVideo` option is defined as:
`String option = video instanceof Apple2015Video ? source_apple_2015 : source_apple_2017;`.

That leads to 2018 and 2019 options ignored (unless they are disabled). E.g. if I disable 2017 source, and set 2019 to `4K HDR`, I'll get `Full HD SDR` instead (default option).

**Comment by cachapa** [comment]
You're right. I really need to rewrite the whole thing...

**Comment by Dreamescaper** [comment]
I can submit a PR with fix later today, if you're ok with that.

**Comment by cachapa** [comment]
Thanks, but I managed to hack around it for now.
After the fix I get the same problem playing HDR videos as I had in the 2017 playlist, which makes sense.

I'll disable HDR again for this release and try to figure out if there's something we're missing to get ExoPlayer to play HDR, or if it's OS/HW related.

**Comment by cachapa** [comment]
To be clear, I'm not proud of the fix, but it works :-)

**Comment by Dreamescaper** [comment]
HDR works for me, if I use SurfaceView instead of TextureView - therefore having to disable fade transition.

**Comment by Dreamescaper** [comment]
Currently fade transition leads to issues for me (bugs #4 and #21 ), so I might work on making in optional, therefore partially allowing HDR videos playback.

**Comment by cachapa** [comment]
Hmm, that might be an avenue worth pursuing.
I was afraid of doing that because it's mean rewriting large portions of the app, but at this point that sounds like a good thing.

Unfortunately I don't have the time to do that. If you'd like to take that work I'd be happy to take PRs, but for such a fundamental change I'd like to have a deeper discussion so we're aligned before you start working.
