### ISSUE TITLE
On load screensavers are flashing green and the video in a jerking behavior

### ISSUE THREAD

**Issue by uratrtl** [cachapa/AerialDream#26]
I've had this issue for a while and I've tried uninstalling Arial Dream, and I even factory reset my 2017 shield and still when I try to use arial dream at any resolution I either get frozen video or a green flashing with jerky video. I have a 4k tv plugged directly into the shield, is anyone else having this issue?

**Comment by rclough** [comment]
I started noticing the same behavior on my 2017 Nvidia shield sometime within the last week or two. Aerial dream will load for a little bit, and eventually the video loops about 1 second of clip with a green flash in between. I mostly use the screensaver while listening to spotify in the background (since its on a TV with burn-in risk), in case that might have anything to do with it.

/cc @cachapa

**Comment by cachapa** [comment]
I just published a new beta version which simply updated the video player to the latest version.
Could you try that and see if it's still showing issues?

**Comment by cachapa** [comment]
I'm closing this issue and following this in #30
