### ISSUE TITLE
Feature request: Audio support

### ISSUE THREAD

**Issue by wrick17** [cachapa/AerialDream#36]
Play some audio (preferably user selected, from a local file or a url) while the screensaver plays.
It would be great if we could select the audio level to tune the sound. Something like lounge audio in the background. Subtle.

**Comment by cachapa** [comment]
Playing audio can be really complex, and I think the effort to implement it would be better spent improving the current app.
It would probably make more sense to use a standard music player to play sounds on the background and then active the screensaver. You'd have a lot more control over the playlist, volume, etc.

I'm also not comfortable with having a screensaver play sound automatically since it can be jarring in a lot of situations (e.g. late at night).

In any case thanks for the suggestion but I will close this ticket since it falls outside the scope of this app.
