### ISSUE TITLE
Cache causes some videos to loop continuously

### ISSUE THREAD

**Issue by lnxpro** [cachapa/AerialDream#7]
While setting cache option at 4GB or 8GB is nice, it does not work properly.
It will cause some of the videos that were partially downloaded to loop continuously and will not go on to next video.
Cache option is nice to have, but please do not remove the option. See if it can get fixed.
Also would be nice to be able to set cache location.
I have a 4TB external drive connected to my nVidia Shield TV so I would love to set the cache location to that, then I wouldn't have to worry about a specific cache size option. The app defaults to some internal location.

**Comment by cachapa** [comment]
Thanks for the report.
If the videos aren't caching properly, this is probably a bug with the ExoPlayer caching mechanism. We would either have to wait for a fix from them or implement a custom caching layer.
Ideally we would report the problem on their issue list, but unfortunately I currently don't have the availability for either solution.

I'll keep this open in order to track it.

**Comment by cachapa** [comment]
There have been since a lot of updates to the video library we're using. Is the caching still causing issues?

Unfortunately I can't test properly myself since I don't have enough free space on my test device.

**Comment by lnxpro** [comment]
Thanks for the update. Unfortunately I am in the middle of buying a new
house so my nvidia shield tv is in the storage for the time being. It will
be a while before I can test.
Thanks though.

**Comment by cachapa** [comment]
@ns5gti I've created a new issue to track that: #17

**Comment by ns5gti** [comment]
thanks

> @ns5gti I've created a new issue to track that: #17

Thanks

**Comment by cachapa** [comment]
Closing this as caching is disabled in latest release.
